name: Add New Issue To Project Board

on:
  issues:
    types:
      - opened
      
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/gowhale/projects/1/
          github-token: ${{ secrets.PROJECT_PAT }}
